CREATE TABLE preliminary(
	as_of_year text,
	respondent_id text,
	agency_name text,
	agency_abbr text,
	agency_code text,
	loan_type_name text,
	loan_type text,
	property_type_name text,
	property_type text,
	loan_purpose_name text,
	loan_purpose text,
	owner_occupancy_name text,
	owner_occupancy text,
	loan_amount_000s text,
	preapproval_name text,
	preapproval text,
	action_taken_name text,
	action_taken text,
	msamd_name text,
	msamd text,
	state_name text,
	state_abbr text,
	state_code text,
	county_name text,
	county_code text,
	census_tract_number text,
	applicant_ethnicity_name text,
	applicant_ethnicity text,
	co_applicant_ethnicity_name text,
	co_applicant_ethnicity text,
	applicant_race_name_1 text,
	applicant_race_1 text,
	applicant_race_name_2 text,
	applicant_race_2 text,
	applicant_race_name_3 text,
	applicant_race_3 text,
	applicant_race_name_4 text,
	applicant_race_4 text,
	applicant_race_name_5 text,
	applicant_race_5 text,
	co_applicant_race_name_1 text,
	co_applicant_race_1 text,
	co_applicant_race_name_2 text,
	co_applicant_race_2 text,
	co_applicant_race_name_3 text,
	co_applicant_race_3 text,
	co_applicant_race_name_4 text,
	co_applicant_race_4 text,
	co_applicant_race_name_5 text,
	co_applicant_race_5 text,
	applicant_sex_name text,
	applicant_sex text,
	co_applicant_sex_name text,
	co_applicant_sex text,
	applicant_income_000s text,
	purchaser_type_name text,
	purchaser_type text,
	denial_reason_name_1 text,
	denial_reason_1 text,
	denial_reason_name_2 text,
	denial_reason_2 text,
	denial_reason_name_3 text,
	denial_reason_3 text,
	rate_spread text,
	hoepa_status_name text,
	hoepa_status text,
	lien_status_name text,
	lien_status text,
	edit_status_name text,
	edit_status text,
	sequence_number text,
	population text,
	minority_population text,
	hud_median_family_income text,
	tract_to_msamd_income text,
	number_of_owner_occupied_units text,
	number_of_1_to_4_family_units text,
	application_date_indicator text
);

COPY preliminary FROM '/Users/edwardwang.wyz/Downloads/hmda_2017_nj_all-records_labels.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE typed_preliminary(
	as_of_year int NOT NULL,
	respondent_id text NOT NULL,
	agency_name text NOT NULL,
	agency_abbr text NOT NULL,
	agency_code int NOT NULL,
	loan_type_name text NOT NULL,
	loan_type int NOT NULL,
	property_type_name text NOT NULL,
	property_type int NOT NULL,
	loan_purpose_name text NOT NULL,
	loan_purpose int NOT NULL,
	owner_occupancy_name text NOT NULL,
	owner_occupancy int NOT NULL,
	loan_amount_000s int,
	preapproval_name text NOT NULL,
	preapproval int NOT NULL,
	action_taken_name text NOT NULL,
	action_taken int NOT NULL,
	msamd_name text,
	msamd int,
	state_name text NOT NULL,
	state_abbr text NOT NULL,
	state_code int NOT NULL,
	county_name text,
	county_code int,
	census_tract_number numeric (6, 2),
	applicant_ethnicity_name text NOT NULL,
	applicant_ethnicity int NOT NULL,
	co_applicant_ethnicity_name text NOT NULL,
	co_applicant_ethnicity int NOT NULL,
	applicant_race_name_1 text NOT NULL,
	applicant_race_1 int NOT NULL,
	applicant_race_name_2 text,
	applicant_race_2 int,
	applicant_race_name_3 text,
	applicant_race_3 int,
	applicant_race_name_4 text,
	applicant_race_4 int,
	applicant_race_name_5 text,
	applicant_race_5 int,
	co_applicant_race_name_1 text NOT NULL,
	co_applicant_race_1 int NOT NULL,
	co_applicant_race_name_2 text,
	co_applicant_race_2 int,
	co_applicant_race_name_3 text,
	co_applicant_race_3 int,
	co_applicant_race_name_4 text,
	co_applicant_race_4 int,
	co_applicant_race_name_5 text,
	co_applicant_race_5 int,
	applicant_sex_name text NOT NULL,
	applicant_sex int NOT NULL,
	co_applicant_sex_name text NOT NULL,
	co_applicant_sex int NOT NULL,
	applicant_income_000s int,
	purchaser_type_name text NOT NULL,
	purchaser_type int NOT NULL,
	denial_reason_name_1 text,
	denial_reason_1 int,
	denial_reason_name_2 text,
	denial_reason_2 int,
	denial_reason_name_3 text,
	denial_reason_3 int,
	rate_spread numeric (4, 2),
	hoepa_status_name text NOT NULL,
	hoepa_status int NOT NULL,
	lien_status_name text NOT NULL,
	lien_status int NOT NULL,
	edit_status_name text,
	edit_status text,
	sequence_number int,
	population int,
	minority_population numeric (20, 15),
	hud_median_family_income int,
	tract_to_msamd_income numeric (20, 15),
	number_of_owner_occupied_units int,
	number_of_1_to_4_family_units int,
	application_date_indicator int
);

INSERT INTO typed_preliminary
SELECT
	NULLIF(as_of_year, '')::int,
	respondent_id,
	agency_name,
	agency_abbr,
	agency_code::int,
	loan_type_name,
	loan_type::int,
	property_type_name,
	property_type::int,
	loan_purpose_name,
	loan_purpose::int,
	owner_occupancy_name,
	owner_occupancy::int,
	NULLIF(loan_amount_000s, '')::int,
	preapproval_name,
	preapproval::int,
	action_taken_name,
	action_taken::int,
	msamd_name,
	NULLIF(msamd, '')::int,
	state_name,
	state_abbr,
	state_code::int,
	county_name,
	NULLIF(county_code, '')::int,
	NULLIF(census_tract_number, '')::numeric(6,2),
	applicant_ethnicity_name,
	applicant_ethnicity::int,
	co_applicant_ethnicity_name,
	NULLIF(co_applicant_ethnicity, '')::int,
	applicant_race_name_1,
	applicant_race_1::int,
	applicant_race_name_2,
	NULLIF(applicant_race_2, '')::int,
	applicant_race_name_3,
	NULLIF(applicant_race_3, '')::int,
	applicant_race_name_4,
	NULLIF(applicant_race_4, '')::int,
	applicant_race_name_5,
	NULLIF(applicant_race_5, '')::int,
	co_applicant_race_name_1,
	co_applicant_race_1::int,
	co_applicant_race_name_2,
	NULLIF(co_applicant_race_2, '')::int,
	co_applicant_race_name_3,
	NULLIF(co_applicant_race_3, '')::int,
	co_applicant_race_name_4,
	NULLIF(co_applicant_race_4, '')::int,
	co_applicant_race_name_5,
	NULLIF(co_applicant_race_5, '')::int,
	applicant_sex_name,
	applicant_sex::int,
	co_applicant_sex_name,
	co_applicant_sex::int,
	NULLIF(applicant_income_000s, '')::int,
	purchaser_type_name,
	purchaser_type::int,
	denial_reason_name_1,
	NULLIF(denial_reason_1, '')::int,
	denial_reason_name_2,
	NULLIF(denial_reason_2, '')::int,
	denial_reason_name_3,
	NULLIF(denial_reason_3, '')::int,
	NULLIF(rate_spread, '')::numeric(4,2),
	hoepa_status_name,
	hoepa_status::int,
	lien_status_name,
	lien_status::int,
	edit_status_name,
	edit_status,
	NULLIF(sequence_number, '')::int,
	NULLIF(population, '')::int,
	NULLIF(minority_population, '')::numeric(20,15),
	NULLIF(hud_median_family_income, '')::int,
	NULLIF(tract_to_msamd_income, '')::numeric(20,15),
	NULLIF(number_of_owner_occupied_units, '')::int,
	NULLIF(number_of_1_to_4_family_units, '')::int,
	NULLIF(application_date_indicator, '')::int
FROM preliminary;

DROP TABLE preliminary;

ALTER TABLE typed_preliminary ADD COLUMN application_id SERIAL PRIMARY KEY;
